-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."flares" add column "isEnabled" boolean
--  null default 'false';
