version: "3.6"
services:
  graphql-engine:
    container_name: reddit-backend
    image: hasura/graphql-engine:v2.16.1
    ports:
      - "8060:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "cGpDnQgwKS4qdjTP60AClmJx9XktM7WZ"}'
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ACTIONS_ENDPOINT: ${HASURA_GRAPHQL_ACTIONS_ENDPOINT}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
